security:
  encoders:
    App\Entity\User:
      algorithm: bcrypt

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: ROLE_ADMIN

  providers:
    entity_provider:
      entity:
        class: App\Entity\User
        property: username

  firewalls:
    api_login:
      pattern:  ^/api/auth/login
      stateless: true
      anonymous: true
      json_login:
        check_path: /api/auth/login
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    register:
      pattern:  ^/api/auth/register
      stateless: true
      anonymous: true

  access_control:
  - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
  - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
  - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
  - { path: ^/admin/, role: ROLE_ADMIN }