monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.symfony.log"
            channels: [event, console, doctrine, security]
        doctrine:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.doctrine.log"
            channels: doctrine
        login:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.auth.log"
            channels: security
        api:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.api.log"
            #level: info
            channels: app